name: release

on:
  push:
    tags:
      - '*'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Print version
        id: "version"
        run: |
          echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=platforms::linux/amd64"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and push when release
        id: release_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ steps.version.outputs.platforms }}
          tags: |
            csust/vortex:latest
            csust/vortex:${{ steps.version.outputs.tag }}

      - 
        name: Image digest
        run: echo ${{ steps.release_build.outputs.digest }}
